import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';

const PREFIX = 'ic_fluent_';
const REGULAR_SUFFIX = '_20_regular';

type IconMap = Record<string, number>;

const scriptDir = (import.meta as any).dir;
const inputPath = resolve(scriptDir, 'FluentSystemIcons-Resizable.json');
const outputPath = resolve(scriptDir, 'icon-codes.ts');

const isRegularIcon = (name: string): boolean => {
  return name.startsWith(PREFIX) && name.endsWith(REGULAR_SUFFIX);
};

const normalizeName = (name: string): string => {
  return name.slice(PREFIX.length, -REGULAR_SUFFIX.length);
};

const run = async (): Promise<void> => {
  const file = await readFile(inputPath, 'utf8');
  const parsed = JSON.parse(file) as IconMap;

  const entries = Object.entries(parsed)
    .filter(([name]) => isRegularIcon(name))
    .map(([name, code]) => [normalizeName(name), code] as const)
    .sort(([left], [right]) => left.localeCompare(right));

  const body = entries.map(([name, code]) => `  ${name}: ${code},`).join('\n');
  const output = [
    '// update from here: https://github.com/microsoft/fluentui-system-icons/blob/main/fonts/FluentSystemIcons-Resizable.json',
    '// generated by: bun run gen-icon-codes',
    'export const iconCodes = {',
    body,
    '}',
    '',
  ].join('\n');

  await writeFile(outputPath, output, 'utf8');
  console.log(`Generated ${entries.length} icons: ${outputPath}`);
};

run().catch((error: unknown) => {
  console.error(error);
  process.exit(1);
});