/* eslint-disable */
/* This file is generated by tools/generate-function-route-map.js. Do not edit by hand. */

import type { Endpoint } from '@root/functions/shared/functions-utils';
import type { ApproveUserFunction } from '@root/functions/api/approve-user';
import type { GenerateJoinLinkFunction } from '@root/functions/api/auth/generate-join-link';
import type { JoinWithProviderFunction } from '@root/functions/api/auth/join-with-provider';
import type { LoginWithPasswordFunction } from '@root/functions/api/auth/login-with-password';
import type { PreviewEmailTemplateFunction } from '@root/functions/api/auth/preview-email-template';
import type { PreviewJoinLinkFunction } from '@root/functions/api/auth/preview-join-link';
import type { RegisterWithPasswordFunction } from '@root/functions/api/auth/register-with-password';
import type { SendInvitationEmailFunction } from '@root/functions/api/auth/send-invitation-email';
import type { SendPasswordResetEmailFunction } from '@root/functions/api/auth/send-password-reset-email';
import type { CreateUnitFunction } from '@root/functions/api/create-unit';
import type { JoinUnitFunction } from '@root/functions/api/join-unit';
import type { ListPostersFunction } from '@root/functions/api/list-posters';
import type { ListUnapprovedUnitsFunction } from '@root/functions/api/list-unapproved-units';
import type { ListUnitsFunction } from '@root/functions/api/list-units';
import type { PresignFileAccessFunction } from '@root/functions/api/presign-file-access';
import type { SetUnitApprovedFunction } from '@root/functions/api/set-unit-approved';
import type { SetUserAdminFunction } from '@root/functions/api/set-user-admin';
import type { UploadFileFunction } from '@root/functions/api/upload-file';

type EndpointParams<TFunction> = TFunction extends Endpoint<infer P, any> ? P : never;
type EndpointResult<TFunction> = TFunction extends Endpoint<any, infer R> ? R : never;

export type FunctionRouteMap = {
    'approve-user': ApproveUserFunction;
    'auth/generate-join-link': GenerateJoinLinkFunction;
    'auth/join-with-provider': JoinWithProviderFunction;
    'auth/login-with-password': LoginWithPasswordFunction;
    'auth/preview-email-template': PreviewEmailTemplateFunction;
    'auth/preview-join-link': PreviewJoinLinkFunction;
    'auth/register-with-password': RegisterWithPasswordFunction;
    'auth/send-invitation-email': SendInvitationEmailFunction;
    'auth/send-password-reset-email': SendPasswordResetEmailFunction;
    'create-unit': CreateUnitFunction;
    'join-unit': JoinUnitFunction;
    'list-posters': ListPostersFunction;
    'list-unapproved-units': ListUnapprovedUnitsFunction;
    'list-units': ListUnitsFunction;
    'presign-file-access': PresignFileAccessFunction;
    'set-unit-approved': SetUnitApprovedFunction;
    'set-user-admin': SetUserAdminFunction;
    'upload-file': UploadFileFunction;
};

export type FunctionRoute = keyof FunctionRouteMap;
export type FunctionParams<TRoute extends FunctionRoute> = EndpointParams<FunctionRouteMap[TRoute]>;
export type FunctionResult<TRoute extends FunctionRoute> = EndpointResult<FunctionRouteMap[TRoute]>;
