
export const DbConstants = {
    public: {
        Enums: {
            shape: [
                "circle",
                "triangle",
                "square",
                "pentagon",
                "hexagon",
                "shapes",
                "oval",
                "rhombus",
                "shape_organic",
                "premium",
                "fire",
                "water",
                "mountain_trail",
                "weather_cloudy",
                "weather_sunny",
                "weather_moon",
                "star",
                "heart",
                "bow_tie",
                "briefcase",
                "guardian",
                "hat_graduation",
                "book",
                "food_fish",
                "lightbulb",
                "key_multiple",
                "compass_northwest",
                "sport",
                "sport_basketball",
                "sport_american_football",
                "sport_soccer",
                "card_ui",
                "dust",
                "tree_deciduous",
                "plant_ragweed",
                "food_grains",
                "hand_right",
                "money",
                "savings",
                "people_audience",
                "doctor",
                "scales",
            ],
        },
    },
} as const;
