export const HYMN_TITLES: Readonly<Record<number, string>> = {
    1: 'Come, Thou Fount of Every Blessing',
    2: 'When the Savior Comes Again',
    3: 'It Is Well with My Soul',
    4: 'I Will Walk with Jesus',
    5: 'His Eye Is on the Sparrow',
    6: 'Think a Sacred Song',
    7: 'As Bread Is Broken',
    8: 'Bread of Life, Living Water',
    9: 'Gethsemane',
    10: 'Amazing Grace',
    11: 'Holding Hands Around the World',
    12: 'Anytime, Anywhere',
    13: 'God’s Gracious Love',
    14: 'My Shepherd Will Supply My Need',
    15: 'Oh, the Deep, Deep Love of Jesus',
    16: 'Behold the Wounds in Jesus’ Hands',
    17: 'This Is the Christ',
    18: 'Come, Lord Jesus',
    19: 'To Love like Thee',
    20: 'Softly and Tenderly Jesus Is Calling',
    21: 'I Know That My Savior Loves Me',
    22: 'Faith in Every Footstep',
    23: 'Standing on the Promises',
    24: 'I Have Faith in the Lord Jesus Christ',
    25: 'Take My Heart and Let It Be Consecrated',
    26: 'Holy Places',
    27: 'Welcome Home',
    28: 'This Little Light of Mine',
    29: 'I Can’t Count Them All',
    30: 'Close as a Quiet Prayer',
    31: 'Come, Hear the Word the Lord Has Spoken',
    32: 'Look unto Christ',
    33: 'Oh, How Great Is Our Joy',
    34: 'I’m a Pioneer Too',
    35: 'As I Keep the Sabbath Day',
    36: 'Read the Book of Mormon and Pray',
    37: 'I’m Gonna Live So God Can Use Me',
    38: 'The Lord’s My Shepherd',
    39: 'Because',
    40: 'His Voice as the Sound',
    41: 'O Lord, Who Gave Thy Life for Me',
    42: 'Thou Gracious God, Whose Mercy Lends',
    43: 'Help Us Remember',
    44: 'How Did the Savior Minister?',
    45: 'Jesus Is the Way',
    46: 'Can You Count the Stars in Heaven?',
    47: 'He Cares for Me',
    48: 'Our Prayer to Thee',
    49: 'Joseph Prayed in Faith',
    50: 'Stand by Me',
    51: 'This Day Is a Good Day, Lord',
    52: 'Joyfully Bound',
    53: 'My Covenants',
    54: 'When I Am Baptized',
    55: 'The Power of the Holy Ghost',
    56: 'Elijah and the Still, Small Voice',
    57: 'Jesus Is My Shepherd',
    58: 'My Song in the Night',
    59: 'This Is My Father’s World',
    60: 'Build an Ark',
    61: 'Love Will Bless Our Home',
    62: 'Lord, Accept Our Humble Fast',
    201: 'Hail the Day That Sees Him Rise',
    202: 'He Is Born, the Divine Christ Child',
    203: 'What Child Is This?',
    204: 'Star Bright',
    205: 'Let Easter Anthems Ring',
    206: 'Were You There?',
    207: 'Still, Still, Still',
    208: 'Go Tell It on the Mountain',
    209: 'Little Baby in a Manger',
    210: 'Long Ago, Within a Garden',
};

export const HYMN_TOPICS: Readonly<Record<string, string>> = {
    'agency': 'agency',
    'trials': 'trials',
    'forgiveness': 'forgiveness',
    'gathering-of-israel': 'gathering of Israel',
    'music': 'music',
    'eternal-life': 'eternal life',
    'work': 'work',
    'song': 'song',
    'discipleship': 'discipleship',
    'missionary-work': 'missionary work',
    'truth': 'truth',
    'fasting': 'fasting',
    'gods-love': "God's love",
    'revelation': 'revelation',
    'preparedness': 'preparedness',
    'supplication': 'supplication',
    'charity': 'charity',
    'happiness': 'happiness',
    'spiritual-gifts': 'spiritual gifts',
    'example': 'example',
    'prayer': 'prayer',
    'heavenly-father': 'Heavenly Father',
    'wisdom': 'wisdom',
    'faith': 'faith',
    'jesus-christ': 'Jesus Christ',
    'resurrection': 'Resurrection',
    'encouragement': 'encouragement',
    'temptation': 'temptation',
    'gratitude': 'gratitude',
    'abrahamic-covenant': 'Abrahamic Covenant',
    'diligence': 'diligence',
    'sorrow': 'sorrow',
    'knowledge': 'knowledge',
    'worthiness': 'worthiness',
    'covenants': 'covenants',
    'gospel': 'gospel',
    'praise': 'praise',
    'opening': 'opening',
    'crucifixion': 'Crucifixion',
    'education': 'Education',
    'grace': 'grace',
    'book-of-mormon': 'Book of Mormon',
    'child-of-god': 'child of God',
    'service': 'service',
    'peace': 'peace',
    'funeral': 'funeral',
    'children': 'children',
    'second-coming': 'Second Coming',
    'trust': 'trust',
    'worship': 'worship',
    'repentance': 'repentance',
    'humility': 'humility',
    'millennium': 'Millennium',
    'commitment': 'commitment',
    'holy-ghost': 'Holy Ghost',
    'love': 'love',
    'youth': 'youth',
    'creation': 'Creation',
    'ministering': 'ministering',
    'baptism': 'baptism',
    'rejoicing': 'rejoicing',
    'family': 'family',
    'mercy': 'mercy',
    'consecration': 'consecration',
    'comfort': 'comfort',
    'old-testament': 'Old Testament',
    'fall-of-adam-and-eve': 'Fall of Adam and Eve',
    'scriptures': 'scriptures',
    'prophets': 'prophets',
    'light-of-christ': 'Light of Christ',
    'trust-in-the-lord': 'trust in the Lord',
    'first-vision': 'First Vision',
    'faith-in-jesus-christ': 'faith in Jesus Christ',
    'hope': 'hope',
    'guidance': 'guidance',
    'testimony': 'testimony',
    'kindness': 'kindness',
    'the-sacrament': 'the sacrament',
    'home': 'home',
    'joy': 'joy',
    'unity': 'unity',
    'blessings': 'blessings',
    'easter': 'Easter',
    'death': 'death',
    'sabbath': 'Sabbath',
    'worldwide-church': 'worldwide Church',
    'cheerfulness': 'cheerfulness',
    'restoration-of-the-church': 'Restoration of the Church',
    'pioneers': 'pioneers',
    'teachers': 'teachers',
    'endure-to-the-end': 'endure to the end',
    'chapel': 'chapel',
    'obedience': 'obedience',
    'sacrifice': 'sacrifice',
    'restoration': 'Restoration',
    'plan-of-salvation': 'plan of salvation',
    'christmas': 'Christmas',
    'tithing': 'tithing',
    'patience': 'patience',
    'fast-offerings': 'fast offerings',
    'assurance': 'assurance',
    'atonement-of-jesus-christ': 'Atonement of Jesus Christ',
    'joseph-smith': 'Joseph Smith',
    'temples': 'temples',
    'commandments': 'commandments',
    'courage': 'courage',
    'adversity': 'adversity',
};
