import type { HymnTopic } from "./hymn-topics";

export type HymnNumber = 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13 | 14 | 15 | 16 | 17 | 18 | 19 | 20 |
    21 | 22 | 23 | 24 | 25 | 26 | 27 | 28 | 29 | 30 | 31 | 32 | 33 | 34 | 35 | 36 | 37 | 38 | 39 | 40 |
    41 | 42 | 43 | 44 | 45 | 46 | 47 | 48 | 49 | 50 | 51 | 52 | 53 | 54 | 55 | 56 | 57 | 58 | 59 | 60 |
    61 | 62 | 201 | 202 | 203 | 204 | 205 | 206 | 207 | 208 | 209 | 210;

export const HYMN_INFO_BY_NUMBER: Readonly<Record<HymnNumber, { slug: string, topics: HymnTopic[] }>> = {
    1: { slug: 'come-thou-fount-of-every-blessing', topics: ['atonement-of-jesus-christ', 'blessings', 'commitment', 'discipleship', 'grace', 'gratitude', 'love', 'mercy', 'praise', 'repentance', 'song', 'temples'] },
    2: { slug: 'when-the-savior-comes-again', topics: ['jesus-christ', 'millennium', 'second-coming', 'children', 'knowledge', 'peace', 'preparedness', 'scriptures'] },
    3: { slug: 'it-is-well-with-my-soul', topics: ['atonement-of-jesus-christ', 'jesus-christ', 'second-coming', 'assurance', 'comfort', 'faith', 'peace', 'praise', 'repentance', 'sorrow', 'the-sacrament', 'trials'] },
    4: { slug: 'i-will-walk-with-jesus', topics: ['holy-ghost', 'jesus-christ', 'children', 'comfort', 'covenants', 'discipleship', 'love', 'repentance', 'trust-in-the-lord', 'truth', 'wisdom', 'youth'] },
    5: { slug: 'his-eye-is-on-the-sparrow', topics: ['jesus-christ', 'adversity', 'assurance', 'comfort', 'commitment', 'happiness', 'peace', 'song', 'trust-in-the-lord'] },
    6: { slug: 'think-a-sacred-song', topics: ['holy-ghost', 'children', 'comfort', 'song'] },
    7: { slug: 'as-bread-is-broken', topics: ['atonement-of-jesus-christ', 'crucifixion', 'holy-ghost', 'jesus-christ', 'sabbath', 'forgiveness', 'grace', 'repentance', 'the-sacrament'] },
    8: { slug: 'bread-of-life-living-water', topics: ['atonement-of-jesus-christ', 'crucifixion', 'jesus-christ', 'covenants', 'forgiveness', 'sacrifice', 'the-sacrament'] },
    9: { slug: 'gethsemane', topics: ['atonement-of-jesus-christ', 'jesus-christ', 'children', 'love', 'the-sacrament'] },
    10: { slug: 'amazing-grace', topics: ['assurance', 'comfort', 'endure-to-the-end', 'grace', 'hope', 'peace', 'praise', 'repentance', 'trials'] },
    11: { slug: 'holding-hands-around-the-world', topics: ['jesus-christ', 'light-of-christ', 'children', 'courage', 'faith', 'family', 'gospel', 'joy', 'song', 'worldwide-church'] },
    12: { slug: 'anytime-anywhere', topics: ['heavenly-father', 'holy-ghost', 'light-of-christ', 'assurance', 'children', 'comfort', 'guidance', 'prayer', 'supplication'] },
    13: { slug: 'gods-gracious-love', topics: ['adversity', 'comfort', 'endure-to-the-end', 'grace', 'love', 'peace', 'trials', 'trust-in-the-lord'] },
    14: { slug: 'my-shepherd-will-supply-my-need', topics: ['old-testament', 'assurance', 'death', 'funeral', 'grace', 'peace', 'praise', 'repentance', 'trust-in-the-lord'] },
    15: { slug: 'oh-the-deep-deep-love-of-jesus', topics: ['atonement-of-jesus-christ', 'jesus-christ', 'blessings', 'charity', 'eternal-life', 'love', 'mercy', 'praise'] },
    16: { slug: 'behold-the-wounds-in-jesus-hands', topics: ['atonement-of-jesus-christ', 'crucifixion', 'fall-of-adam-and-eve', 'comfort', 'forgiveness', 'grace', 'love', 'repentance', 'the-sacrament'] },
    17: { slug: 'this-is-the-christ', topics: ['atonement-of-jesus-christ', 'book-of-mormon', 'love', 'testimony', 'the-sacrament', 'worship'] },
    18: { slug: 'come-lord-jesus', topics: ['christmas', 'second-coming', 'comfort', 'mercy', 'supplication'] },
    19: { slug: 'to-love-like-thee-release-3', topics: ['blessings', 'charity', 'love', 'ministering', 'missionary-work', 'prayer', 'service'] },
    20: { slug: 'softly-and-tenderly-jesus-is-calling-release-3', topics: ['jesus-christ', 'endure-to-the-end', 'forgiveness', 'love', 'mercy', 'patience', 'repentance'] },
    21: { slug: 'i-know-that-my-savior-loves-me-release-3', topics: ['book-of-mormon', 'jesus-christ', 'blessings', 'children', 'guidance', 'love', 'obedience', 'teachers', 'testimony'] },
    22: { slug: 'faith-in-every-footstep-release-3', topics: ['restoration', 'courage', 'discipleship', 'faith', 'gathering-of-israel', 'missionary-work', 'pioneers', 'service', 'work'] },
    23: { slug: 'standing-on-the-promises-release-3', topics: ['abrahamic-covenant', 'holy-ghost', 'jesus-christ', 'covenants', 'discipleship', 'love', 'peace', 'praise', 'trust-in-the-lord'] },
    24: { slug: 'i-have-faith-in-the-lord-jesus-christ-release-3', topics: ['light-of-christ', 'agency', 'children', 'commandments', 'faith-in-jesus-christ', 'love', 'obedience'] },
    25: { slug: 'take-my-heart-and-let-it-be-consecrated-release-3', topics: ['jesus-christ', 'consecration', 'discipleship', 'love', 'music', 'praise', 'service', 'song'] },
    26: { slug: 'holy-places-release-3', topics: ['holy-ghost', 'jesus-christ', 'chapel', 'covenants', 'endure-to-the-end', 'grace', 'home', 'love', 'temples', 'trials', 'unity'] },
    27: { slug: 'welcome-home-release-3', topics: ['jesus-christ', 'chapel', 'covenants', 'endure-to-the-end', 'grace', 'love', 'opening', 'temples', 'trials', 'unity'] },
    28: { slug: 'this-little-light-of-mine-release-3', topics: ['jesus-christ', 'light-of-christ', 'children', 'example', 'ministering', 'missionary-work', 'testimony'] },
    29: { slug: 'i-cant-count-them-all-release-3', topics: ['jesus-christ', 'blessings', 'comfort', 'grace', 'gratitude', 'love', 'mercy', 'praise'] },
    30: { slug: 'close-as-a-quiet-prayer-release-3', topics: ['heavenly-father', 'children', 'comfort', 'gratitude', 'love', 'praise', 'prayer'] },
    31: { slug: 'come-hear-the-word-the-lord-has-spoken-release-3', topics: ['jesus-christ', 'millennium', 'restoration-of-the-church', 'second-coming', 'gratitude', 'music', 'opening', 'praise', 'rejoicing', 'revelation'] },
    32: { slug: 'look-unto-christ', topics: ['jesus-christ', 'adversity', 'commitment', 'courage', 'encouragement', 'endure-to-the-end', 'faith-in-jesus-christ', 'hope', 'trials', 'trust-in-the-lord'] },
    33: { slug: 'oh-how-great-is-our-joy', topics: ['light-of-christ', 'gathering-of-israel', 'joy', 'love', 'missionary-work', 'rejoicing', 'service', 'teachers', 'work'] },
    34: { slug: 'im-a-pioneer-too', topics: ['courage', 'discipleship', 'pioneers', 'sacrifice', 'work', 'worldwide-church'] },
    35: { slug: 'as-i-keep-the-sabbath-day', topics: ['gods-love', 'sabbath', 'commandments', 'covenants', 'gratitude', 'obedience', 'peace', 'worship'] },
    36: { slug: 'read-the-book-of-mormon-and-pray', topics: ['book-of-mormon', 'education', 'jesus-christ', 'diligence', 'faith-in-jesus-christ', 'guidance', 'prayer', 'scriptures', 'testimony'] },
    37: { slug: 'im-gonna-live-so-god-can-use-me', topics: ['commitment', 'consecration', 'discipleship', 'music', 'prayer', 'service', 'work'] },
    38: { slug: 'the-lords-my-shepherd', topics: ['jesus-christ', 'assurance', 'blessings', 'comfort', 'courage', 'funeral', 'guidance', 'hope', 'peace', 'trust-in-the-lord'] },
    39: { slug: 'because', topics: ['gods-love', 'second-coming', 'blessings', 'gratitude', 'hope', 'love', 'peace', 'praise'] },
    40: { slug: 'his-voice-as-the-sound', topics: ['comfort', 'discipleship', 'faith-in-jesus-christ', 'grace', 'love', 'mercy', 'praise', 'worship'] },
    41: { slug: 'o-lord-who-gave-thy-life-for-me', topics: ['commitment', 'discipleship', 'endure-to-the-end', 'faith-in-jesus-christ', 'forgiveness', 'grace', 'humility', 'love', 'mercy', 'repentance', 'sacrifice', 'supplication', 'the-sacrament', 'trust'] },
    42: { slug: 'thou-gracious-god-whose-mercy-lends', topics: ['gratitude', 'mercy', 'supplication', 'trust-in-the-lord'] },
    43: { slug: 'help-us-remember', topics: ['atonement-of-jesus-christ', 'humility', 'repentance', 'the-sacrament'] },
    44: { slug: 'how-did-the-savior-minister', topics: ['charity', 'discipleship', 'ministering', 'service'] },
    45: { slug: 'jesus-is-the-way', topics: ['discipleship', 'eternal-life', 'gospel', 'truth'] },
    46: { slug: 'can-you-count-the-stars-in-heaven', topics: ['creation', 'gods-love', 'heavenly-father', 'child-of-god', 'prayer'] },
    47: { slug: 'he-cares-for-me', topics: ['gods-love', 'heavenly-father', 'assurance', 'child-of-god', 'prayer'] },
    48: { slug: 'our-prayer-to-thee', topics: ['heavenly-father', 'gratitude', 'prayer', 'worship'] },
    49: { slug: 'joseph-prayed-in-faith', topics: ['first-vision', 'joseph-smith', 'prayer', 'trust-in-the-lord'] },
    50: { slug: 'stand-by-me', topics: ['adversity', 'temptation', 'trials', 'trust-in-the-lord'] },
    51: { slug: 'this-day-is-a-good-day-lord', topics: ['cheerfulness', 'peace', 'praise', 'scriptures', 'worship'] },
    52: { slug: 'joyfully-bound', topics: ['baptism', 'blessings', 'covenants', 'rejoicing', 'temples', 'the-sacrament'] },
    53: { slug: 'my-covenants', topics: ['holy-ghost', 'baptism', 'covenants', 'discipleship', 'guidance', 'obedience', 'service'] },
    54: { slug: 'when-i-am-baptized', topics: ['baptism', 'eternal-life', 'forgiveness', 'plan-of-salvation', 'worthiness'] },
    55: { slug: 'the-power-of-the-holy-ghost', topics: ['holy-ghost', 'guidance', 'revelation', 'testimony'] },
    56: { slug: 'elijah-and-the-still-small-voice', topics: ['holy-ghost', 'old-testament', 'assurance', 'comfort', 'peace', 'prayer', 'revelation', 'spiritual-gifts'] },
    57: { slug: 'jesus-is-my-shepherd', topics: ['gods-love', 'assurance', 'comfort', 'faith-in-jesus-christ', 'guidance', 'kindness', 'trust-in-the-lord'] },
    58: { slug: 'my-song-in-the-night', topics: ['jesus-christ', 'assurance', 'comfort', 'music', 'prayer', 'trials'] },
    59: { slug: 'this-is-my-fathers-world', topics: ['creation', 'heavenly-father', 'assurance', 'cheerfulness', 'comfort', 'gratitude', 'praise', 'trust-in-the-lord'] },
    60: { slug: 'build-an-ark', topics: ['courage', 'faith-in-jesus-christ', 'obedience', 'prayer', 'preparedness', 'prophets'] },
    61: { slug: 'love-will-bless-our-home', topics: ['gods-love', 'assurance', 'comfort', 'encouragement', 'endure-to-the-end', 'family', 'home', 'peace'] },
    62: { slug: 'lord-accept-our-humble-fast', topics: ['charity', 'consecration', 'fast-offerings', 'fasting', 'humility', 'sacrifice', 'service', 'tithing'] },
    201: { slug: 'hail-the-day-that-sees-him-rise', topics: ['easter', 'jesus-christ', 'resurrection', 'love', 'praise'] },
    202: { slug: 'he-is-born-the-divine-christ-child', topics: ['christmas', 'jesus-christ', 'grace', 'prophets', 'song'] },
    203: { slug: 'what-child-is-this', topics: ['atonement-of-jesus-christ', 'christmas', 'crucifixion', 'jesus-christ', 'joy', 'praise', 'rejoicing'] },
    204: { slug: 'star-bright', topics: ['book-of-mormon', 'christmas', 'jesus-christ', 'light-of-christ', 'assurance', 'children', 'joy', 'love', 'mercy'] },
    205: { slug: 'let-easter-anthems-ring-release-3', topics: ['easter', 'jesus-christ', 'resurrection', 'grace', 'praise', 'rejoicing'] },
    206: { slug: 'were-you-there-release-3', topics: ['crucifixion', 'easter', 'jesus-christ', 'resurrection', 'the-sacrament'] },
    207: { slug: 'still-still-still', topics: ['christmas', 'gods-love', 'jesus-christ', 'peace', 'praise'] },
    208: { slug: 'go-tell-it-on-the-mountain', topics: ['christmas', 'jesus-christ', 'missionary-work', 'rejoicing'] },
    209: { slug: 'little-baby-in-a-manger', topics: ['christmas', 'praise', 'worship'] },
    210: { slug: 'long-ago-within-a-garden', topics: ['atonement-of-jesus-christ', 'crucifixion', 'easter', 'fall-of-adam-and-eve', 'resurrection', 'forgiveness', 'plan-of-salvation', 'repentance'] },
};
