
export const HYMN_TITLES: Readonly<Record<number, string>> = {
    1: 'Komm, du Quelle jedes Segens',
    2: 'Wenn der Heiland wiederkehrt',
    3: 'Meine Seel findet Ruhe im Herrn',
    4: 'Auf dem Weg mit Jesus',
    5: 'Er wacht auch über mich',
    6: 'Denke an ein Lied',
    7: 'Wenn still das Brot nun gebrochen wird',
    8: 'Lebensbrot, Quell des Lebens',
    9: 'Getsemani',
    10: 'Die Gnade sein',
    11: 'Weltweit Hand in Hand',
    12: 'Jederzeit, überall',
    13: 'Tag für Tag',
    14: 'Du, Herr, bist mein geliebter Hirt',
    15: 'O wie tief die Liebe Jesu',
    16: 'Die Nägelmale Jesu seht',
    17: 'Es ist der Herr',
    18: 'Komm, Herr Jesus',
    19: 'Hilf mir, zu lieben, Herr, wie du',
    20: 'Gütig und liebevoll ruft uns der Heiland',
    21: 'Ich weiß, dass mein Heiland mich liebt',
    22: 'Mit jedem Schritt im Glauben',
    23: 'Standhaft baue ich auf Gottes Wort',
    24: 'Jesus lebt',
    25: 'Nimm mein Herz, ich weih es dir',
    26: 'Heilige Stätten',
    27: 'Willkommen zuhaus',
    28: 'Mein kleines Licht scheint hell',
    29: 'Unzählige Gaben',
    30: 'Nur ein Gebet entfernt',
    31: 'O kommt und hört das Wort des Heilands',
    32: 'Blick auf zum Herrn',
    33: 'Freudig gehn wir hinaus in die Welt',
    34: 'Ein Pionier kann jeder sein',
    35: 'Ich halt heilig seinen Tag',
    36: 'Im Buch Mormon lesen macht mich stark',
    37: 'Ich lebe so, dass ich Gott diene',
    38: '',
    39: '',
    40: '',
    41: '',
    42: '',
    43: '',
    44: '',
    45: '',
    46: '',
    47: '',
    48: '',
    49: '',
    50: '',
    51: '',
    52: '',
    53: '',
    54: '',
    55: '',
    56: '',
    57: '',
    58: '',
    59: '',
    60: '',
    61: '',
    62: '',
    201: 'Preist den Herrn, der auferstand',
    202: 'Christus ist geboren heut',
    203: 'Wen wiegt Maria sanft im Arm?',
    204: 'Erstrahle, du Stern',
    205: 'Das Osterlied erschall!',
    206: 'Warst du da, als sie kreuzigten den Herrn?',
    207: 'Still, Still, Still',
    208: '',
    209: '',
    210: '',
};

export const HYMN_TOPICS: Readonly<Record<string, string>> = {
    'agency': 'Entscheidungsfreiheit',
    'trials': 'Prüfungen',
    'forgiveness': 'Vergebung',
    'gathering-of-israel': 'Sammlung Israels',
    'music': 'Musik',
    'eternal-life': 'ewiges Leben',
    'work': 'Arbeit',
    'song': 'Lied',
    'discipleship': 'Nachfolge Christi',
    'missionary-work': 'Missionsarbeit',
    'truth': 'Wahrheit',
    'fasting': 'Fasten',
    'gods-love': "Gottes Liebe",
    'revelation': 'Offenbarung',
    'preparedness': 'Vorbereitetsein',
    'supplication': 'Flehen',
    'charity': 'Nächstenliebe',
    'happiness': 'Glücklichsein',
    'spiritual-gifts': 'Geistige Gaben',
    'example': 'Vorbild',
    'prayer': 'Gebet',
    'heavenly-father': 'Vater im Himmel',
    'wisdom': 'Weisheit',
    'faith': 'Glaube',
    'jesus-christ': 'Jesus Christus',
    'resurrection': 'Auferstehung',
    'encouragement': 'Ermutigung',
    'temptation': 'Versuchung',
    'gratitude': 'Dankbarkeit',
    'abrahamic-covenant': 'Bund mit Abraham',
    'diligence': 'Eifer',
    'sorrow': 'Kummer',
    'knowledge': 'Wissen',
    'worthiness': 'Würdigkeit',
    'covenants': 'Bündnisse',
    'gospel': 'Evangelium',
    'praise': 'Lobpreis',
    'opening': 'Anfangslieder',
    'crucifixion': 'Kreuzigung',
    'education': 'Wissenserwerb',
    'grace': 'Gnade',
    'book-of-mormon': 'Buch Mormon',
    'child-of-god': 'Kind Gottes',
    'service': 'Dienen',
    'peace': 'Frieden',
    'funeral': 'Beerdigung',
    'children': 'Kinder',
    'second-coming': 'Zweites Kommen',
    'trust': 'Vertrauen',
    'worship': 'Gottesverehrung',
    'repentance': 'Umkehr',
    'humility': 'Demut',
    'millennium': 'Millennium',
    'commitment': 'Entschlossenheit',
    'holy-ghost': 'Heiliger Geist',
    'love': 'Liebe',
    'youth': 'Jugendliche',
    'creation': 'Schöpfung',
    'ministering': 'geistlich dienen',
    'baptism': 'Taufe',
    'rejoicing': 'jubeln',
    'family': 'Familie',
    'mercy': 'Barmherzigkeit',
    'consecration': 'Weihung',
    'comfort': 'Trost',
    'old-testament': 'Altes Testament',
    'fall-of-adam-and-eve': 'Fall Adams und Evas',
    'scriptures': 'heilige Schriften',
    'prophets': 'Propheten',
    'light-of-christ': 'Licht Christi',
    'trust-in-the-lord': 'Gottvertrauen',
    'first-vision': 'Erste Vision',
    'faith-in-jesus-christ': 'Glaube an Jesus Christus',
    'hope': 'Hoffnung',
    'guidance': 'Führung',
    'testimony': 'Zeugnis',
    'kindness': 'Freundlichkeit',
    'the-sacrament': 'Abendmahl',
    'home': 'Zuhause',
    'joy': 'Freude',
    'unity': 'Einigkeit',
    'blessings': 'Segnungen',
    'easter': 'Ostern',
    'death': 'Tod',
    'sabbath': 'Sabbat',
    'worldwide-church': 'Kirche in aller Welt',
    'cheerfulness': 'Fröhlichkeit',
    'restoration-of-the-church': 'Wiederherstellung der Kirche',
    'pioneers': 'Pioniere',
    'teachers': 'Lehrer',
    'endure-to-the-end': 'Ausharren bis ans Ende',
    'chapel': 'Kapelle',
    'obedience': 'Gehorsam',
    'sacrifice': 'Opfer',
    'restoration': 'Wiederherstellung',
    'plan-of-salvation': 'Plan der Erlösung',
    'christmas': 'Weihnachten',
    'tithing': 'Zehnter',
    'patience': 'Geduld',
    'fast-offerings': 'Fastopfer',
    'assurance': 'Zusicherung',
    'atonement-of-jesus-christ': 'Sühnopfer Jesu Christi',
    'joseph-smith': 'Joseph Smith',
    'temples': 'Tempel',
    'commandments': 'Gebote',
    'courage': 'Mut',
    'adversity': 'Widrigkeiten',
};
